Select UNIQUECARRIER,sum(ArrDelay) as x , absolute_error(x),relative_error(x) from airline group by UNIQUECARRIER with error 0.04 confidence 0.95 behavior 'PARTIAL_RUN_ON_BASE_TABLE';
Select UNIQUECARRIER,avg(ArrDelay) as x , absolute_error(x),relative_error(x) from airline group by UNIQUECARRIER with error 0.02 confidence 0.95 behavior 'PARTIAL_RUN_ON_BASE_TABLE';
Select UNIQUECARRIER,avg(ArrDelay) as x , absolute_error(x),relative_error(x) from airline group by UNIQUECARRIER order by UNIQUECARRIER with error 0.04 confidence 0.95 behavior 'PARTIAL_RUN_ON_BASE_TABLE';
Select UNIQUECARRIER,sum(ArrDelay) as x , absolute_error(x),relative_error(x) from airline group by UNIQUECARRIER order by UNIQUECARRIER with error 0.04 confidence 0.95 behavior 'PARTIAL_RUN_ON_BASE_TABLE';
Select UNIQUECARRIER,sum(ArrDelay) as x , absolute_error(x),relative_error(x) from airline group by UNIQUECARRIER with error 0.04 confidence 0.95 behavior 'RUN_ON_FULL_TABLE';
Select UNIQUECARRIER,avg(ArrDelay) as x , absolute_error(x),relative_error(x) from airline group by UNIQUECARRIER with error 0.02 confidence 0.95 behavior 'RUN_ON_FULL_TABLE';
Select UNIQUECARRIER,avg(ArrDelay) as x , absolute_error(x),relative_error(x) from airline group by UNIQUECARRIER order by UNIQUECARRIER with error 0.04 confidence 0.95 behavior 'RUN_ON_FULL_TABLE';
Select UNIQUECARRIER,sum(ArrDelay) as x , absolute_error(x),relative_error(x) from airline group by UNIQUECARRIER order by UNIQUECARRIER with error 0.04 confidence 0.95 behavior 'RUN_ON_FULL_TABLE';
Select UNIQUECARRIER,sum(ArrDelay) as x , absolute_error(x),relative_error(x) from airline group by UNIQUECARRIER with error 0.04 confidence 0.95 behavior 'DO_NOTHING';
Select UNIQUECARRIER,avg(ArrDelay) as x , absolute_error(x),relative_error(x) from airline group by UNIQUECARRIER with error 0.02 confidence 0.95 behavior 'DO_NOTHING';
Select UNIQUECARRIER,avg(ArrDelay) as x , absolute_error(x),relative_error(x) from airline group by UNIQUECARRIER order by UNIQUECARRIER with error 0.04 confidence 0.95 behavior 'DO_NOTHING';
Select UNIQUECARRIER,sum(ArrDelay) as x , absolute_error(x),relative_error(x) from airline group by UNIQUECARRIER order by UNIQUECARRIER with error 0.04 confidence 0.95 behavior 'DO_NOTHING';
Select UNIQUECARRIER,sum(ArrDelay) as x , absolute_error(x),relative_error(x) from airline group by UNIQUECARRIER;
Select UNIQUECARRIER,avg(ArrDelay) as x , absolute_error(x),relative_error(x) from airline group by UNIQUECARRIER;
Select UNIQUECARRIER,avg(ArrDelay) as x , absolute_error(x),relative_error(x) from airline group by UNIQUECARRIER order by UNIQUECARRIER;
Select UNIQUECARRIER,sum(ArrDelay) as x , absolute_error(x),relative_error(x) from airline group by UNIQUECARRIER order by UNIQUECARRIER;
